// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-generations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_generations_default = defineTool({
  name: "list_recent_generations",
  title: "List recent generations",
  description: "List the signed-in user's most recent Viralin AI generation requests (image or video) with status and result URLs.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many recent requests to return."),
    status: z.enum(["pending", "processing", "completed", "failed"]).nullable().describe("Optional status filter. Null returns all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let query = sb.from("generation_requests").select("id, request_type, category, status, prompt, result_url, created_at, credits_used").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { requests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-credit-balance.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_credit_balance_default = defineTool2({
  name: "get_credit_balance",
  title: "Get credit balance",
  description: "Return the signed-in user's Viralin AI credit balance: monthly limit, credits used this period, remaining credits, subscription tier, and bonus credits.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("profiles").select(
      "email, display_name, subscription_tier, monthly_generation_limit, generations_this_month, bonus_credits"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Profile not found" }], isError: true };
    }
    const limit = Number(data.monthly_generation_limit ?? 0);
    const used = Number(data.generations_this_month ?? 0);
    const bonus = Number(data.bonus_credits ?? 0);
    const remaining = Math.max(0, limit - used) + bonus;
    const summary = { ...data, credits_remaining: remaining };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-posting-history.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.49.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_posting_history_default = defineTool3({
  name: "list_posting_history",
  title: "List posting history",
  description: "List the signed-in user's recent Creative Workflow posts (concept, platforms, status, scheduled_for) from the posting history.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("How many recent posts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("creative_posts").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mkwinxbualpcivkujlfd";
var mcp_default = defineMcp({
  name: "viralin-ai-mcp",
  title: "Viralin AI",
  version: "0.1.0",
  instructions: "Tools for Viralin AI. Read the signed-in user's generation history, credit balance, and Creative Workflow posting history.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_generations_default, get_credit_balance_default, list_posting_history_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
