// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkwinxbualpcivkujlfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rd2lueGJ1YWxwY2l2a3VqbGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTU1MTAsImV4cCI6MjA1ODIzMTUxMH0.GK4ljHmyWStpkHWwsdLH7_22BzqNSeWSLCRSV9lWndc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);